language: php

php:
  - 5.4
  - 5.5

before_script:
    - composer self-update
    - composer install --dev
    - cp .atoum.php.dist .atoum.php

script: vendor/bin/atoum --test-all

notifications:
  email: "deronmalian+travis-ci@gmail.com"
